package codeanalysis;

/**
 * The EmitResult class represents the result of bytecode emission.
 * It contains the generated bytecode and any associated diagnostics.
 *
 * @see <a href="https://github.com/urunsiyabend">GitHub Profile</a>
 * @author Siyabend Urun
 * @version 1.0
 */
public class EmitResult {
    private final DiagnosticBox _diagnostics;
    private final byte[] _bytecode;

    /**
     * Creates a new instance of the EmitResult class with the specified diagnostics and bytecode.
     *
     * @param diagnostics The diagnostics associated with the emission.
     * @param bytecode    The generated bytecode, or null if there were errors.
     */
    public EmitResult(DiagnosticBox diagnostics, byte[] bytecode) {
        _diagnostics = diagnostics;
        _bytecode = bytecode;
    }

    /**
     * Retrieves the diagnostics box associated with the emit result.
     *
     * @return The diagnostics.
     */
    public DiagnosticBox diagnostics() {
        return _diagnostics;
    }

    /**
     * Retrieves the generated bytecode.
     *
     * @return The bytecode, or null if there were errors.
     */
    public byte[] getBytecode() {
        return _bytecode;
    }

    /**
     * Checks if the emission was successful (no diagnostics).
     *
     * @return True if successful, false otherwise.
     */
    public boolean isSuccess() {
        return !_diagnostics.hasNext();
    }
}
